# Site settings
title: Elegant Thought Blog
email: ""
description: >
 Elegant Thoughts blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.elegantthought.com" # the base hostname & protocol for your site
twitter_username: ElegantThought
github_username:  ElegantThought

# Build settings
markdown: kramdown
